# Tests with USeful Algorithms

## Floodfill

Work in progress...

In [3]:
import numpy as np

def flood_fill_3d(volume, start_xyz, new_value):
    # Get the initial value at the start coordinates
    x, y, z = start_xyz
    old_value = volume[x, y, z]
    if old_value == new_value:
        return volume

    # Define the stack and initialize with the start position
    stack = [(x, y, z)]

    # Loop as long as there are elements in the stack
    while stack:
        x, y, z = stack.pop()
        
        # Check if the current position is within bounds
        if x < 0 or x >= volume.shape[0] or y < 0 or y >= volume.shape[1] or z < 0 or z >= volume.shape[2]:
            continue

        # Change the value if it matches the old value
        if volume[x, y, z] == old_value:
            volume[x, y, z] = new_value
            
            # Add the six neighbors (up, down, left, right, front, back)
            stack.append((x + 1, y, z))
            stack.append((x - 1, y, z))
            stack.append((x, y + 1, z))
            stack.append((x, y - 1, z))
            stack.append((x, y, z + 1))
            stack.append((x, y, z - 1))
    
    return volume

## Example 1

# Example of a 3D volume
volume = np.array([[[0, 0, 0], [0, 0, 0], [0, 0, 0]],
                   [[0, 0, 0], [1, 1, 1], [0, 0, 0]],
                   [[0, 0, 0], [0, 0, 0], [0, 0, 0]]])

# Starting point and the new value to fill
start_xyz = (1, 1, 1)
new_value = 2

# Execute the flood fill algorithm
filled_volume = flood_fill_3d(volume, start_xyz, new_value)
print(filled_volume)

## Example 2

# Create a larger, more interesting 5x5x5 volume
volume = np.zeros((5, 5, 5), dtype=int)

# Define different regions in the volume
volume[1:4, 1:4, 1:4] = 1  # Inner cube
volume[2, 2, :] = 2        # Middle cross slice in z-direction with different value

print("Initial Volume:")
print(volume[:, :, 2])  # Display a central slice for simplicity

# Starting point within the inner cube, not on the cross, and new value to fill
start_xyz = (2, 2, 1)  # Starting from a value of 1, but not the center cross
new_value = 3

# Execute the flood fill algorithm
filled_volume = flood_fill_3d(volume, start_xyz, new_value)

print("Modified Volume:")
print(filled_volume[:, :, 2])  # Display the same central slice to show changes

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [2 2 2]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
Initial Volume:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 2 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
Modified Volume:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 3 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
