# VPS Tests with Numpy

These are my first trials to replicate VPS using Numpy.

## Pointshell

We generate the following data:

- A numpy array of shape (10000, 6) which contains random floats in [-1.0, 1.0]; the first 3 columns denote point coordinates, whereas the last 3 columns denote normal vectors. Thus, the 6D elements are points in space each with a normal vector. Additionally, we constrain the first 3 floats to be in a unit sphere (i.e., a sphere with radius 1); we achieve that by projecting the point coordinates onto the unit sphere.
- A numpy array of shape (4,4) containing floats: this array/matrix is in reality a homogeneous transformation matrix H composed by a rotation matrix R (3,3) and a translation vector t (3,1) side by side. Note that the last row of the matrix should be [0.0, 0.0, 0.0, 1.0], since it's a homogeneous transformation matrix; maybe, instead of working with the H (4,4) matrix, we could work with two arrays: R (3,3) and t (3,1). The R part is be orthonormal, i.e., R*transpose(R) = Identity and determinant(R) = 1.0.

In [6]:
import numpy as np

# Function to generate a point on a unit sphere
def generate_on_unit_sphere(n_points):
    vec = np.random.randn(n_points, 3)  # Generate random points in 3D
    vec /= np.linalg.norm(vec, axis=1)[:, np.newaxis]  # Normalize points to lie on the surface of a unit sphere
    return vec

# Generate 10000 points with their normals
points = generate_on_unit_sphere(10000)
normals = np.random.uniform(-1.0, 1.0, (10000, 3))  # Generate random normal vectors
data = np.hstack((points, normals))  # Concatenate points and normals

# Function to generate a random orthonormal matrix, i.e., a rotation matrix
def random_rotation_matrix():
    # Create a random unit quaternion
    q = np.random.randn(4)
    q /= np.linalg.norm(q)

    # Convert the quaternion into a rotation matrix
    q0, q1, q2, q3 = q
    R = np.array([[1 - 2*q2**2 - 2*q3**2, 2*q1*q2 - 2*q3*q0, 2*q1*q3 + 2*q2*q0],
                  [2*q1*q2 + 2*q3*q0, 1 - 2*q1**2 - 2*q3**2, 2*q2*q3 - 2*q1*q0],
                  [2*q1*q3 - 2*q2*q0, 2*q2*q3 + 2*q1*q0, 1 - 2*q1**2 - 2*q2**2]])
    return R

# Generate a random rotation matrix R
R = random_rotation_matrix()

# Generate a random translation vector t
t = np.random.uniform(-1.0, 1.0, (3, 1))

# Construct the homogeneous transformation matrix H
H = np.eye(4)
H[:3, :3] = R
H[:3, 3] = t.ravel()

(data, H)


(array([[-0.53196706, -0.80591067,  0.25984426,  0.90534519, -0.32349198,
          0.615199  ],
        [ 0.32513339,  0.27802857, -0.9038741 , -0.99189268,  0.60095333,
          0.6915906 ],
        [ 0.10523909,  0.18194573,  0.97766072,  0.00888023,  0.35102678,
          0.14932224],
        ...,
        [-0.70382975,  0.5198727 ,  0.48410336,  0.75023236, -0.23744527,
         -0.23797059],
        [-0.55661276,  0.71852731,  0.41701407,  0.24300842, -0.0555407 ,
          0.25912546],
        [ 0.67597756, -0.4823948 , -0.5570903 , -0.17260041,  0.07464767,
          0.01977732]]),
 array([[ 0.09340405,  0.55734346, -0.82501149, -0.24756895],
        [-0.85362758, -0.38166107, -0.35447819, -0.42990918],
        [-0.51244087,  0.73736226,  0.44011505, -0.65278671],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]))

Now we use R and t to transform data as follows:

- Apply the transformation H to all points in the first 3 columns of data (the points), i.e., new_point = R*point + t
- Apply only the rotation T to the last 3 columns of data (the normals), i.e., new_normal = R*normal

We do it in a function transform_data() which takes as input the data and the H matrix. The function returns the transformed data. However, we do not make any copies. Instead, the input data is modified in place.

We perform 1000 transformations with a unique random H matrix and measure how long the average transform_data() requires.

In [11]:
import time

# Function to transform data in place according to the provided homogeneous transformation matrix H
def transform_data(data, H, start=None, stop=None):
    R = H[:3, :3]  # Extract the rotation matrix
    t = H[:3, 3]   # Extract the translation vector

    # Determine slice range
    start = start if start is not None else 0
    stop = stop if stop is not None else data.shape[0]

    # Apply transformation to points within the specified slice
    # FIXME: maybe we should return data_transformed
    data[start:stop, :3] = np.dot(data[start:stop, :3], R.T) + t

    # Apply rotation to normals within the specified slice
    # FIXME: maybe we should return data_transformed
    data[start:stop, 3:] = np.dot(data[start:stop, 3:], R.T)

# Measure performance
start_time = time.time()
for _ in range(1000):
    R = random_rotation_matrix()  # Generate a new random rotation matrix
    t = np.random.uniform(-1.0, 1.0, (3, 1))  # Generate a new random translation vector

    # Construct a new homogeneous transformation matrix H
    H_new = np.eye(4)
    H_new[:3, :3] = R
    H_new[:3, 3] = t.ravel()

    # Transform the data
    # We can transform the complete set of points or a slice start:stop
    start = int(0.0*data.shape[0])
    stop = int(0.99*data.shape[0])
    transform_data(data, H_new, start=start, stop=stop)

end_time = time.time()
average_time = (end_time - start_time) / 1000

average_time # 0.00036285042762756347

0.000549536943435669

## Voxelmap and Collision

Now we create a class called Environment (Voxelmap) which will contain a Numpy array called map of shape (Nx, Ny, Nz) with random integer values (int16, signed). N values are passed when the class is instantiated. The class also takes the float tuples (xMin, yMin, zMin) and (xMax, yMax, zMax) and save them as the arrays bbox_min and bbox_max of shape (3,).

Additionally, we need a method compute_collision() which takes as input the transformed beforehand data array (10000, 6). Then, the first 3 columns of the data array (points) are checked against the map as follows: 

- The real 3 coordinates of every point p in data are transformed into the discrete map array coordinates using bbox_min and bbox_max: real in data (px, py, pz) -> discrete in map (PX, PY, PZ).
- We create an array of shape (10000, 1) (i.e., in practice the same number of rows as data) which contains 0.0 floats; we call that array penetration and each point as an entry.
- Then, the integer value in the map is observed in the discrete coordinates: map[PX, PY, PZ]; if that value is larger than 0, the corresponding point entry in the penetration array gets assigned the map[PX, PY, PZ] value.
- Finally, the penetration array is multiplied to the last 3 columns of data (normals) one by one and the products are summed. The resulting (1,3) array is the collision force, which is returned by compute_collision().

We should not use any loops. Instead, use numpy operators only to be as fast as possible.

In [3]:
import numpy as np

class Environment:
    def __init__(self, N, bbox_min, bbox_max):
        self.map = np.random.randint(np.iinfo(np.int16).min, np.iinfo(np.int16).max + 1, N, dtype=np.int16)
        self.bbox_min = np.array(bbox_min)
        self.bbox_max = np.array(bbox_max)

    def compute_collision(self, data, start=None, stop=None):
        # Determine slice range
        start = start if start is not None else 0
        stop = stop if stop is not None else data.shape[0]

        # Scale factors for converting real coordinates to discrete map indices
        scale_factors = (self.map.shape - np.array([1, 1, 1])) / (self.bbox_max - self.bbox_min)

        # Convert real coordinates in the specified slice of data to discrete coordinates in the map
        # TODO: store distance from voxel center to point and project it in normal to correct map_value
        discrete_coords = ((data[start:stop, :3] - self.bbox_min) * scale_factors).astype(int)

        # Clamp coordinates to map bounds
        discrete_coords = np.clip(discrete_coords, [0, 0, 0], np.array(self.map.shape) - 1)

        # Fetch map values at discrete coordinates without using a loop
        map_values = self.map[discrete_coords[:, 0], discrete_coords[:, 1], discrete_coords[:, 2]]

        # Update penetration values based on map values
        # TODO: get max/min penetration/distance
        # TODO: make penetration/distance array a property that can be accessed
        penetration = np.where(map_values > 0, map_values, 0).reshape(-1, 1)

        # Compute collision force for the specified slice
        # TODO: compute torque approximations
        collision_force = np.sum(penetration * data[start:stop, 3:], axis=0)

        return collision_force.reshape((1, 3))

# Example of class instantiation and method usage
N = (100, 100, 100)  # Map dimensions
bbox_min = (-5.0, -5.0, -5.0)  # Minimum bounds
bbox_max = (5.0, 5.0, 5.0)  # Maximum bounds

env = Environment(N, bbox_min, bbox_max)

# For demonstration purposes, let's create a sample data array similar to the previously transformed data
data_sample = np.random.uniform(-1.0, 1.0, (10000, 6))
data_sample[:, :3] /= np.linalg.norm(data_sample[:, :3], axis=1)[:, np.newaxis]  # Normalize first 3 columns to unit vectors

# Compute the collision force
collision_force = env.compute_collision(data_sample)
collision_force

array([[ 387627.86741652, -461220.64411773,  643402.43760574]])

Now we run compute_collision(data_sample) 1000 times and measure the average time it takes.

In [4]:
import time

# Measure performance of the optimized compute_collision method again, now with time module imported
start_time_optimized = time.time()

for _ in range(1000):
    start = int(0.0*data_sample.shape[0])
    stop = int(0.99*data_sample.shape[0])
    env.compute_collision(data_sample, start=start, stop=stop)

end_time_optimized = time.time()
average_time_optimized = (end_time_optimized - start_time_optimized) / 1000

average_time_optimized


0.0006852850914001465

## Types

Since each time step is independent from the other and we don't accumulate the error from previous steps in the computation, maybe using `np.float16` is good choice for both the Voxelmap and the Pointshell. It has 2 bytes and maybe it's part of the IEEE 754 standard and is also known as half precision:

- **Precision:** `np.float16` provides less precision compared to more commonly used formats like `np.float32` (single precision) and `np.float64` (double precision). 
- **Exponent and Mantissa:** It has 1 sign bit, 5 exponent bits, and 10 mantissa bits.
- **Range:** The range of numbers that can be represented is approximately from (6.1 x 10^{-5}) to (6.5 X 10^{4}) in absolute values, with the actual precision and exact range varying slightly due to the characteristics of floating-point arithmetic, like subnormal numbers and the handling of special values like NaN (Not a Number) and infinity.
- **Usage:** This data type is often used in applications where memory bandwidth is more critical than precision, such as in mobile devices, lower-power devices, or for certain types of machine learning models where the model size needs to be reduced without a significant drop in accuracy.

With that accuracy it makes sense to define model coordinates in m, while we expect from them:

- Not to exceed 2m in width.
- To have a precission of 1 mm approximately.

**However, the tests below show that the broadcasting operations with `float32` values are several times faster! This is probably system/platform-dependent...**

In [58]:
import numpy as np

numbers = [1.0005, 2.005, 5.0006, 9.0008]
float16_array = np.array(numbers, dtype=np.float16)

print("Array with dtype=np.float16:", float16_array)

Array with dtype=np.float16: [1.001 2.006 5.    9.   ]


In [59]:
numbers = [0.1005, 0.9003, 0.3006, -0.5008]
float16_array = np.array(numbers, dtype=np.float16)

print("Array with dtype=np.float16:", float16_array)

Array with dtype=np.float16: [ 0.1005  0.9004  0.3005 -0.501 ]


In [60]:
numbers = [-0.000015, -0.000023, -0.000056, -0.000098]
float16_array = np.array(numbers, dtype=np.float16)

print("Array with dtype=np.float16:", float16_array)

Array with dtype=np.float16: [-1.5e-05 -2.3e-05 -5.6e-05 -9.8e-05]


In [65]:
import numpy as np
import time

size = 1_000_000  # Large array size for benchmarking

# Generate large arrays
array_float16 = np.random.randn(size).astype(np.float16)
array_float32 = np.random.randn(size).astype(np.float32)
array_float64 = np.random.randn(size).astype(np.float64)

# Time an operation using np.float16
start_time = time.time()
result_float16 = array_float16 * np.float16(2) + np.float16(1)
end_time = time.time()
print(f"Time for np.float16: {end_time - start_time} seconds")

# Time an operation using np.float32
start_time = time.time()
result_float32 = array_float32 * np.float32(2) + np.float32(1)
end_time = time.time()
print(f"Time for np.float32: {end_time - start_time} seconds")

# Time the same operation using np.float64
start_time = time.time()
result_float64 = array_float64 * np.float64(2) + np.float64(1)
end_time = time.time()
print(f"Time for np.float64: {end_time - start_time} seconds")

Time for np.float16: 0.02685999870300293 seconds
Time for np.float32: 0.003380298614501953 seconds
Time for np.float64: 0.004864215850830078 seconds
